@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>Video</b> (haDes:Video)" as haDes_Video [[#haDes%3AVideo]]
class "<b>DVD</b> (haDes:DVD)" as haDes_DVD [[#haDes%3ADVD]]
class "<b>DVDChapter</b> (haDes:DVDChapter)" as haDes_DVDChapter [[#haDes%3ADVDChapter]]
class "<b>Audio</b> (haDes:Audio)" as haDes_Audio [[#haDes%3AAudio]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[../../terms/fr#skos%3AConcept]]
class "<b>porteur physique</b> (haObj:PhysicalCarrier)" as haObj_PhysicalCarrier [[#haObj%3APhysicalCarrier]]
class "<b>emplacement de stockage</b> (premis:StorageLocation)" as premis_StorageLocation [[#premis%3AStorageLocation]]
class "<b>représentation de porteur</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[#haObj%3ACarrierRepresentation]]
class "<b>représentation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]




haDes_DVD --> haDes_DVDChapter :a une partie [0..*]  > 


haDes_DVDChapter : Numéro de chapitre DVD : <i>xsd:nonNegativeInteger</i> [1..1]
haDes_DVDChapter --> haDes_DVD :fait partie de [1..1]  > 






haObj_PhysicalCarrier --|> premis_StorageLocation #blue;line.dotted;text:blue

haObj_PhysicalCarrier : réduction du bruit audio : <i>xsd:string</i> [0..1]
haObj_PhysicalCarrier --> skos_Concept :iec-60094 type [0..1]  \lvitesse d'enregistrement audio [0..1]  > 


haObj_CarrierRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_CarrierRepresentation : nombre de pistes audio : <i>xsd:nonNegativeInteger</i> [0..1]
haObj_CarrierRepresentation : nombre de pistes audio : <i>xsd:nonNegativeInteger</i> [0..1]



hide circle
hide methods
hide empty members
@enduml


