@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>bestand</b> (premis:File)" as premis_File [[#premis%3AFile]]
class "<b>object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>bestandsformaat</b> (dcterms:FileFormat)" as dcterms_FileFormat [[#dcterms%3AFileFormat]]
class "<b>digitale representatie</b> (haObj:DigitalRepresentation)" as haObj_DigitalRepresentation [[#haObj%3ADigitalRepresentation]]
class "<b>representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>fixity</b> (premis:Fixity)" as premis_Fixity [[#premis%3AFixity]]
class "<b>fysieke representatie</b> (haObj:PhysicalRepresentation)" as haObj_PhysicalRepresentation [[#haObj%3APhysicalRepresentation]]
class "<b>representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>lokale identificatie</b> (haObj:LocalIdentifier)" as haObj_LocalIdentifier [[#haObj%3ALocalIdentifier]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>entiteit</b> (prov:Entity)" as prov_Entity [[#prov%3AEntity]]
class "<b>opslagmedium</b> (premis:StorageMedium)" as premis_StorageMedium [[#premis%3AStorageMedium]]
class "<b>opslagplaats</b> (premis:StorageLocation)" as premis_StorageLocation [[#premis%3AStorageLocation]]
class "<b>representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]

premis_File --|> premis_Object #blue;line.dotted;text:blue

premis_File : heeft (bestands)grootte : <i>xsd:nonNegativeInteger</i> [0..1]
premis_File : heeft originele naam : <i>xsd:string</i> [0..1]
premis_File : mime type : <i>xsd:string</i> [0..1]
premis_File --> dcterms_FileFormat :formaat [1..1]  > 
premis_File --> haObj_DigitalRepresentation :heeft media fragment [0..*]  \lis inbegrepen in [1..*]  > 
premis_File --> premis_File :documenteert [0..*]  \lvervangt [0..*]  \lvolgende bestand in volgorde [0..1]  > 
premis_File --> premis_Fixity :heeft fixity [1..1]  > 
premis_File --> premis_StorageLocation :opgeslagen te [1..*]  > 





haObj_DigitalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_DigitalRepresentation --> haObj_PhysicalRepresentation :heeft een bron [0..*]  > 
haObj_DigitalRepresentation --> premis_File :bevat [1..*]  \lbron van het mediafragment (MediaFragment) [0..*]  \lligt aan de basis van [0..*]  > 
haObj_DigitalRepresentation --> premis_IntellectualEntity :is archiefmaster van [1..*]  \lis mezzanineformaat van [0..1]  \lis toegangskopie van [0..1]  \lrepresenteert [1..*]  > 


premis_Fixity : checksum maker : <i>xsd:string</i> [0..*]
premis_Fixity : fixity checksum : <i>xsd:string</i> [1..*]


haObj_PhysicalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_PhysicalRepresentation --> premis_StorageMedium :heeft als medium [0..*]  > 

premis_IntellectualEntity --|> premis_Object #blue;line.dotted;text:blue

premis_IntellectualEntity --> haObj_DigitalRepresentation :heeft archiefmaster [0..1]  \lheeft mezzanineformaat [0..1]  \lheeft toegangskopie [0..*]  > 
premis_IntellectualEntity --> haObj_LocalIdentifier :lokale identifier [0..*]  > 
premis_IntellectualEntity --> premis_IntellectualEntity :heeft onderdeel [0..*]  \lmaakt onderdeel uit van [0..*]  > 
premis_IntellectualEntity --> premis_Representation :wordt gerepresenteerd door [0..*]  > 

haObj_LocalIdentifier --|> skos_Concept #blue;line.dotted;text:blue

haObj_LocalIdentifier : waarde : <i>xsd:string</i> [1..1]


premis_Object --|> prov_Entity #blue;line.dotted;text:blue

premis_Object --> premis_Object :heeft een relatie [0..*]  > 




premis_StorageLocation : opslagpad : <i>xsd:string</i> [1..*]
premis_StorageLocation --> premis_StorageMedium :opslagmedium [0..*]  > 


premis_Representation --|> premis_Object #blue;line.dotted;text:blue



hide circle
hide methods
hide empty members
@enduml


