@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>archive component</b> (schema:ArchiveComponent)" as schema_ArchiveComponent [[#schema%3AArchiveComponent]]
class "<b>creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>collection</b> (schema:Collection)" as schema_Collection [[#schema%3ACollection]]
class "<b>creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[../../terms/en#skos%3AConcept]]
class "<b>content partner</b> (haOrg:ContentPartner)" as haOrg_ContentPartner [[../../organization/en#haOrg%3AContentPartner]]
class "<b>organization</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>creative work series</b> (schema:CreativeWorkSeries)" as schema_CreativeWorkSeries [[#schema%3ACreativeWorkSeries]]
class "<b>creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>digital representation</b> (haObj:DigitalRepresentation)" as haObj_DigitalRepresentation [[#haObj%3ADigitalRepresentation]]
class "<b>representation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>episode</b> (schema:Episode)" as schema_Episode [[#schema%3AEpisode]]
class "<b>creative work</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>organization</b> (org:Organization)" as org_Organization [[../../organization/en#org%3AOrganization]]
class "<b>person</b> (schema:Person)" as schema_Person [[../../organization/en#schema%3APerson]]
class "<b>physical representation</b> (haObj:PhysicalRepresentation)" as haObj_PhysicalRepresentation [[#haObj%3APhysicalRepresentation]]
class "<b>representation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>place</b> (schema:Place)" as schema_Place [[#schema%3APlace]]
class "<b>quantitative Value</b> (schema:QuantitativeValue)" as schema_QuantitativeValue [[#schema%3AQuantitativeValue]]
class "<b>role</b> (schema:Role)" as schema_Role [[#schema%3ARole]]

schema_ArchiveComponent --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_ArchiveComponent : description : <i>xsd:string</i> [1..1]
schema_ArchiveComponent : name : <i>xsd:string</i> [1..1]


schema_Collection --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_Collection : collection size : <i>xsd:integer</i> [0..n]
schema_Collection : description : <i>xsd:string</i> [1..1]
schema_Collection : identifier : <i>xsd:string</i> [1..1]
schema_Collection : name : <i>xsd:string</i> [1..1]
schema_Collection --> premis_IntellectualEntity :has part [0..n]  > 





haOrg_ContentPartner --|> org_Organization #blue;line.dotted;text:blue


schema_CreativeWorkSeries --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_CreativeWorkSeries : description : <i>xsd:string</i> [1..1]
schema_CreativeWorkSeries : identifier : <i>xsd:string</i> [1..1]
schema_CreativeWorkSeries : name : <i>xsd:string</i> [1..1]
schema_CreativeWorkSeries : season number : <i>xsd:integer</i> [0..n]



haObj_DigitalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_DigitalRepresentation : caption : <i>xsd:string</i> [0..1]
haObj_DigitalRepresentation : date created : <i>edtf:EDTF-level1</i> [1..1]
haObj_DigitalRepresentation : description : <i>xsd:string</i> [1..1]
haObj_DigitalRepresentation : identifier : <i>xsd:string</i> [1..1]
haObj_DigitalRepresentation : name : <i>xsd:string</i> [1..1]
haObj_DigitalRepresentation : transcription : <i>xsd:string</i> [0..1]

haObj_DigitalRepresentation --> schema_Role :author [0..n]  > 


schema_Episode --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_Episode : description : <i>xsd:string</i> [1..1]
schema_Episode : identifier : <i>xsd:string</i> [1..1]
schema_Episode : name : <i>xsd:string</i> [1..1]


premis_IntellectualEntity --|> premis_Object #blue;line.dotted;text:blue

premis_IntellectualEntity : about : <i>IRI</i> [0..n]
premis_IntellectualEntity : abstract : <i>xsd:string</i> [0..1]
premis_IntellectualEntity : alternate name : <i>xsd:string</i> [0..n]
premis_IntellectualEntity : copyright notice : <i>xsd:string</i> [0..n]
premis_IntellectualEntity : copyright year : <i>xsd:integer</i> [0..n]
premis_IntellectualEntity : credit text : <i>xsd:string</i> [0..n]
premis_IntellectualEntity : date available : <i>xsd:dateTime</i> [0..n]
premis_IntellectualEntity : date created : <i>edtf:EDTF-level1</i> [0..1]
premis_IntellectualEntity : date published : <i>edtf:EDTF-level1</i> [0..1]
premis_IntellectualEntity : description : <i>xsd:string</i> [1..1]
premis_IntellectualEntity : duration : <i>xsd:dateTime</i> [0..1]
premis_IntellectualEntity : genre : <i>xsd:string</i> [0..n]
premis_IntellectualEntity : identifier : <i>xsd:string</i> [1..1]
premis_IntellectualEntity : in language : <i>xsd:string</i> [1..n]
premis_IntellectualEntity : keywords : <i>xsd:string</i> [0..n]
premis_IntellectualEntity : name : <i>xsd:string</i> [1..1]
premis_IntellectualEntity : temporal : <i>rdf:langString</i> [0..n]


premis_IntellectualEntity --> haOrg_ContentPartner :maintainer [1..1]  > 
premis_IntellectualEntity --> org_Organization :copyright holder [0..n]  > 

premis_IntellectualEntity --> schema_ArchiveComponent :is part of [0..n]  > 
premis_IntellectualEntity --> schema_CreativeWorkSeries :is part of [0..n]  > 
premis_IntellectualEntity --> schema_Episode :is part of [0..n]  > 
premis_IntellectualEntity --> schema_Person :copyright holder [0..n]  > 
premis_IntellectualEntity --> schema_Place :spatial [0..n]  > 
premis_IntellectualEntity --> schema_Role :author [0..n]  \lcontributor [0..n]  \lpublisher [0..n]  > 
premis_IntellectualEntity --> skos_Concept :license [0..n]  > 








haObj_PhysicalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_PhysicalRepresentation : art medium : <i>xsd:string</i> [0..n]
haObj_PhysicalRepresentation : artform : <i>xsd:string</i> [0..n]
haObj_PhysicalRepresentation : description : <i>xsd:string</i> [1..1]
haObj_PhysicalRepresentation : format : <i>xsd:string</i> [1..1]
haObj_PhysicalRepresentation : identifier : <i>xsd:string</i> [1..1]
haObj_PhysicalRepresentation : medium : <i>xsd:string</i> [1..n]
haObj_PhysicalRepresentation : name : <i>xsd:string</i> [1..1]
haObj_PhysicalRepresentation --> schema_QuantitativeValue :depth [0..n]  \lheight [0..n]  \lwidth [0..n]  > 



schema_Place : description : <i>xsd:string</i> [1..1]
schema_Place : name : <i>xsd:string</i> [1..1]



schema_QuantitativeValue : unit code : <i>xsd:string</i> [0..n]
schema_QuantitativeValue : unit text : <i>xsd:string</i> [0..n]
schema_QuantitativeValue : value : <i>xsd:float</i> [0..n]




schema_Role : role name : <i>xsd:string</i> [1..n]
schema_Role --> org_Organization :author [0..n]  \lcontributor [0..n]  \lpublisher [0..n]  > 
schema_Role --> schema_Person :actor [0..n]  \lauthor [0..n]  \lcontributor [0..n]  \lpublisher [0..n]  > 
schema_Role --> skos_Concept :role name [1..n]  > 



hide circle
hide methods
hide empty members
@enduml


