@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 100
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left


class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Fysieke representatie</b> (haObj:PhysicalRepresentation)" as haObj_PhysicalRepresentation [[#haObj%3APhysicalRepresentation]]
class "<b>Representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Digitale representatie</b> (haObj:DigitalRepresentation)" as haObj_DigitalRepresentation [[#haObj%3ADigitalRepresentation]]
class "<b>Representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Bestand</b> (premis:File)" as premis_File [[#premis%3AFile]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Fixity</b> (premis:Fixity)" as premis_Fixity [[#premis%3AFixity]]
class "<b>Opslagplaats</b> (premis:StorageLocation)" as premis_StorageLocation [[#premis%3AStorageLocation]]
class "<b>Lokale identificatie</b> (haObj:LocalIdentifier)" as haObj_LocalIdentifier [[#haObj%3ALocalIdentifier]]
class "<b>Opslagmedium</b> (premis:StorageMedium)" as premis_StorageMedium [[#premis%3AStorageMedium]]
class "<b>Bestandsformaat</b> (dct:FileFormat)" as dct_FileFormat [[#dct%3AFileFormat]]
class "<b>Representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]



premis_Object --> premis_Object : heeft een relatie [0..n] >

premis_IntellectualEntity --|> premis_Object #blue;line.dotted;text:blue


premis_IntellectualEntity --> haObj_DigitalRepresentation : heeft archiefmaster [0..1] >

premis_IntellectualEntity --> haObj_DigitalRepresentation : heeft mezzanineformaat [0..1] >

premis_IntellectualEntity --> premis_IntellectualEntity : heeft onderdeel [0..n] >

premis_IntellectualEntity --> haObj_DigitalRepresentation : heeft toegangskopie [0..n] >

premis_IntellectualEntity --> haObj_LocalIdentifier : lokale identifier [0..n] >

premis_IntellectualEntity --> premis_IntellectualEntity : maakt onderdeel uit van [0..n] >

premis_IntellectualEntity --> premis_Representation : wordt gerepresenteerd door [0..n] >

haObj_PhysicalRepresentation --|> premis_Representation #blue;line.dotted;text:blue


haObj_PhysicalRepresentation --> premis_StorageMedium : heeft als medium [0..n] >

haObj_DigitalRepresentation --|> premis_Representation #blue;line.dotted;text:blue


haObj_DigitalRepresentation --> premis_File : Bron van het mediafragment [0..n] >

haObj_DigitalRepresentation --> premis_File : bevat [1..n] >

haObj_DigitalRepresentation --> haObj_PhysicalRepresentation : heeft een bron [0..n] >

haObj_DigitalRepresentation --> premis_IntellectualEntity : is archiefmaster van [1..n] >

haObj_DigitalRepresentation --> premis_IntellectualEntity : is mezzanineformaat van [0..1] >

haObj_DigitalRepresentation --> premis_IntellectualEntity : is toegangskopie van [0..1] >

haObj_DigitalRepresentation --> premis_File : ligt aan de basis van [0..n] >

haObj_DigitalRepresentation --> premis_IntellectualEntity : representeert [1..n] >

premis_File --|> premis_Object #blue;line.dotted;text:blue


premis_File --> dct_FileFormat : Formaat [1..1] >

premis_File --> premis_File : documenteert [0..n] >

premis_File --> premis_Fixity : heeft fixity [1..1] >

premis_File --> haObj_DigitalRepresentation : heeft media fragment [0..n] >

premis_File --> haObj_DigitalRepresentation : is inbegrepen in [1..n] >
premis_File : mime type : <i>xsd:string</i> [0..1]


premis_File --> premis_StorageLocation : opgeslagen te [1..n] >

premis_File --> premis_File : vervangt [0..n] >

premis_File --> premis_File : volgende bestand in volgorde [0..1] >


premis_Fixity : checksum maker : <i>xsd:string</i> [0..n]

premis_Fixity : fixity checksum : <i>xsd:string</i> [1..n]




premis_StorageLocation --> premis_StorageMedium : opslagmedium [0..n] >
premis_StorageLocation : opslagpad : <i>xsd:string</i> [1..n]



haObj_LocalIdentifier : waarde : <i>xsd:string</i> [1..1]






premis_Representation --|> premis_Object #blue;line.dotted;text:blue



hide circle
hide methods
hide empty members
@enduml


