@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left


class "<b>Collectie</b> (skos:Collection)" as skos_Collection [[#skos%3ACollection]]
class "<b>Geordende collectie</b> (skos:OrderedCollection)" as skos_OrderedCollection [[#skos%3AOrderedCollection]]
class "<b>Collectie</b> (skos:Collection)" as skos_Collection [[#skos%3ACollection]]
class "<b>Concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>Conceptscheme</b> (skos:ConceptScheme)" as skos_ConceptScheme [[#skos%3AConceptScheme]]
class "(skosxl:Label)" as skosxl_Label [[#skosxl%3ALabel]]
class "(rdf:List)" as rdf_List [[#rdf%3AList]]


skos_Collection : alternatief label : <i>rdf:langString</i> [0..n]
skos_Collection : definitie : <i>xsd:string</i> [1..n]
skos_Collection : historische notitie : <i>xsd:string</i> [0..n]
skos_Collection : notation : <i>xsd:string</i> [0..n]
skos_Collection : note : <i>xsd:string</i> [0..n]
skos_Collection : redactionele notitie : <i>xsd:string</i> [0..n]
skos_Collection : scope notitie : <i>xsd:string</i> [0..n]
skos_Collection : verborgen label : <i>rdf:langString</i> [0..n]
skos_Collection : voorbeeld : <i>xsd:string</i> [0..n]
skos_Collection : voorkeurslabel : <i>rdf:langString</i> [1..n]
skos_Collection : wijzigingsnotitie : <i>xsd:string</i> [0..n]

skos_Collection --> skos_Collection :lid [0..n]  > 
skos_Collection --> skos_Concept :lid [0..n]  > 


skos_OrderedCollection --|> skos_Collection #blue;line.dotted;text:blue

skos_OrderedCollection : alternatief label : <i>rdf:langString</i> [0..n]
skos_OrderedCollection : definitie : <i>xsd:string</i> [1..n]
skos_OrderedCollection : historische notitie : <i>xsd:string</i> [0..n]
skos_OrderedCollection : notation : <i>xsd:string</i> [0..n]
skos_OrderedCollection : note : <i>xsd:string</i> [0..n]
skos_OrderedCollection : redactionele notitie : <i>xsd:string</i> [0..n]
skos_OrderedCollection : scope notitie : <i>xsd:string</i> [0..n]
skos_OrderedCollection : verborgen label : <i>rdf:langString</i> [0..n]
skos_OrderedCollection : voorbeeld : <i>xsd:string</i> [0..n]
skos_OrderedCollection : voorkeurslabel : <i>rdf:langString</i> [1..n]
skos_OrderedCollection : wijzigingsnotitie : <i>xsd:string</i> [0..n]
skos_OrderedCollection --> rdf_List :lijst van leden [0..n]  > 




skos_Concept : alternatief label : <i>rdf:langString</i> [0..n]
skos_Concept : definitie : <i>xsd:string</i> [1..n]
skos_Concept : historische notitie : <i>xsd:string</i> [0..n]
skos_Concept : notation : <i>xsd:string</i> [0..n]
skos_Concept : note : <i>xsd:string</i> [0..n]
skos_Concept : redactionele notitie : <i>xsd:string</i> [0..n]
skos_Concept : scope notitie : <i>xsd:string</i> [0..n]
skos_Concept : scope notitie : <i>xsd:string</i> [0..n]
skos_Concept : scope note : <i>rdf:langString</i> [0..n]
skos_Concept : verborgen label : <i>rdf:langString</i> [0..n]
skos_Concept : voorbeeld : <i>xsd:string</i> [0..n]
skos_Concept : voorkeurslabel : <i>rdf:langString</i> [1..n]
skos_Concept : wijzigingsnotitie : <i>xsd:string</i> [0..n]

skos_Concept --> skos_Concept :brede match [0..n]  \lbreder [0..n]  \lbreder transitief [0..n]  \lexacte overeenkomst [0..n]  \lgerelateerde match [0..n]  \lmapping relatie [0..n]  \lnabije match [0..n]  \lnauwe match [0..n]  \lnauwer [0..n]  \lnauwer transitief [0..n]  \lsemantische relatie [0..n]  > 
skos_Concept --> skos_ConceptScheme :in schema [1..n]  \ltop concept van [0..n]  > 
skos_Concept --> skosxl_Label :voorkeurslabel [1..n]  > 



skos_ConceptScheme : alternatief label : <i>rdf:langString</i> [0..n]
skos_ConceptScheme : definitie : <i>xsd:string</i> [1..n]
skos_ConceptScheme : historische notitie : <i>xsd:string</i> [0..n]
skos_ConceptScheme : notation : <i>xsd:string</i> [0..n]
skos_ConceptScheme : note : <i>xsd:string</i> [0..n]
skos_ConceptScheme : redactionele notitie : <i>xsd:string</i> [0..n]
skos_ConceptScheme : scope notitie : <i>xsd:string</i> [0..n]
skos_ConceptScheme : verborgen label : <i>rdf:langString</i> [0..n]
skos_ConceptScheme : voorbeeld : <i>xsd:string</i> [0..n]
skos_ConceptScheme : voorkeurslabel : <i>rdf:langString</i> [1..n]
skos_ConceptScheme : wijzigingsnotitie : <i>xsd:string</i> [0..n]

skos_ConceptScheme --> skos_Concept :heeft top concept [0..n]  > 



skosxl_Label : alternatief label : <i>rdf:langString</i> [0..n]
skosxl_Label : definitie : <i>xsd:string</i> [1..n]
skosxl_Label : historische notitie : <i>xsd:string</i> [0..n]
skosxl_Label : letterlijke vorm : <i>rdf:langString</i> [1..1]
skosxl_Label : notation : <i>xsd:string</i> [0..n]
skosxl_Label : note : <i>xsd:string</i> [0..n]
skosxl_Label : redactionele notitie : <i>xsd:string</i> [0..n]
skosxl_Label : scope notitie : <i>xsd:string</i> [0..n]
skosxl_Label : verborgen label : <i>rdf:langString</i> [0..n]
skosxl_Label : voorbeeld : <i>xsd:string</i> [0..n]
skosxl_Label : voorkeurslabel : <i>rdf:langString</i> [1..n]
skosxl_Label : wijzigingsnotitie : <i>xsd:string</i> [0..n]






hide circle
hide methods
hide empty members
@enduml


