@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>OpenCaptions</b> (ebucore:OpenCaptions)" as ebucore_OpenCaptions [[#ebucore%3AOpenCaptions]]
class "<b>Beeldspoel</b> (haDes:ImageReel)" as haDes_ImageReel [[#haDes%3AImageReel]]
class "<b>Concept</b> (skos:Concept)" as skos_Concept [[../../terms/nl#skos%3AConcept]]
class "<b>Drager representatie</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[../../audiovisual/nl#haObj%3ACarrierRepresentation]]
class "<b>Representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Film</b> (haDes:Film)" as haDes_Film [[#haDes%3AFilm]]
class "<b>Geluidsspoel</b> (haDes:AudioReel)" as haDes_AudioReel [[#haDes%3AAudioReel]]


ebucore_OpenCaptions : in taal : <i>xsd:string</i> [0..*]



haDes_ImageReel --> ebucore_OpenCaptions :heeft (ingebedde) ondertiteling [0..*]  > 
haDes_ImageReel --> skos_Concept :type kleuring [0..1]  > 



haObj_CarrierRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_CarrierRepresentation : aantal (film)rollen/-spoelen : <i>xsd:decimal</i> [0..1]
haObj_CarrierRepresentation : aantal verloren audiorollen/-spoelen : <i>xsd:decimal</i> [0..1]
haObj_CarrierRepresentation : aantal verloren beeldrollen/-spoelen : <i>xsd:decimal</i> [0..1]
haObj_CarrierRepresentation --> haDes_AudioReel :opgeslagen op [1..*]  > 
haObj_CarrierRepresentation --> haDes_ImageReel :opgeslagen op [1..*]  > 



haDes_Film --> haObj_CarrierRepresentation :wordt gerepresenteerd door [1..*]  > 




hide circle
hide methods
hide empty members
@enduml


