@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>OpenCaptions</b> (ebucore:OpenCaptions)" as ebucore_OpenCaptions [[#ebucore%3AOpenCaptions]]
class "<b>Beeldspoel</b> (haFil:ImageReel)" as haFil_ImageReel [[#haFil%3AImageReel]]
class "<b>Film</b> (haFil:Film)" as haFil_Film [[#haFil%3AFilm]]
class "<b>Geluidsspoel</b> (haFil:AudioReel)" as haFil_AudioReel [[#haFil%3AAudioReel]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[../../terms/nl#skos%3AConcept]]
class "<b>drager representatie</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[../../objects/nl#haObj%3ACarrierRepresentation]]
class "<b>representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]


ebucore_OpenCaptions : in taal : <i>xsd:string</i> [0..*]



haFil_ImageReel --> ebucore_OpenCaptions :heeft (ingebedde) ondertiteling [0..*]  > 
haFil_ImageReel --> skos_Concept :type kleuring [0..1]  > 


haFil_Film --> haObj_CarrierRepresentation :wordt gerepresenteerd door [1..*]  > 





haObj_CarrierRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_CarrierRepresentation : aantal (film)rollen/-spoelen : <i>xsd:decimal</i> [0..1]
haObj_CarrierRepresentation : aantal verloren audiorollen/-spoelen : <i>xsd:decimal</i> [0..1]
haObj_CarrierRepresentation : aantal verloren beeldrollen/-spoelen : <i>xsd:decimal</i> [0..1]
haObj_CarrierRepresentation --> haFil_AudioReel :opgeslagen op [1..*]  > 
haObj_CarrierRepresentation --> haFil_ImageReel :opgeslagen op [1..*]  > 



hide circle
hide methods
hide empty members
@enduml


