@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>emplacement de stockage</b> (premis:StorageLocation)" as premis_StorageLocation [[#premis%3AStorageLocation]]
class "<b>entité intellectuelle</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>objet</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>fichier</b> (premis:File)" as premis_File [[#premis%3AFile]]
class "<b>objet</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>fixité</b> (premis:Fixity)" as premis_Fixity [[#premis%3AFixity]]
class "<b>format de fichier</b> (dct:FileFormat)" as dct_FileFormat [[#dct%3AFileFormat]]
class "<b>identifiant local</b> (haObj:LocalIdentifier)" as haObj_LocalIdentifier [[#haObj%3ALocalIdentifier]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>objet</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>entité</b> (prov:Entity)" as prov_Entity [[#prov%3AEntity]]
class "<b>représentation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>objet</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>représentation digitale</b> (haObj:DigitalRepresentation)" as haObj_DigitalRepresentation [[#haObj%3ADigitalRepresentation]]
class "<b>représentation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>représentation physique</b> (haObj:PhysicalRepresentation)" as haObj_PhysicalRepresentation [[#haObj%3APhysicalRepresentation]]
class "<b>représentation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>support de stockage</b> (premis:StorageMedium)" as premis_StorageMedium [[#premis%3AStorageMedium]]


premis_StorageLocation : chemin du fichier : <i>xsd:string</i> [1..n]
premis_StorageLocation --> premis_StorageMedium :a un support [0..n]  > 


premis_IntellectualEntity --|> premis_Object #blue;line.dotted;text:blue

premis_IntellectualEntity --> haObj_DigitalRepresentation :a copie d'accès [0..n]  \la copie principale [0..1]  \la format mezzanine [0..1]  > 
premis_IntellectualEntity --> haObj_LocalIdentifier :identificateur local [0..n]  > 
premis_IntellectualEntity --> premis_IntellectualEntity :a partie [0..n]  \lfait partie de [0..n]  > 
premis_IntellectualEntity --> premis_Representation :est représenté par [0..n]  > 

premis_File --|> premis_Object #blue;line.dotted;text:blue

premis_File : mime type : <i>xsd:string</i> [0..1]
premis_File --> dct_FileFormat :format [1..1]  > 
premis_File --> haObj_DigitalRepresentation :a le fragment des médias [0..n]  \lest inclus dans [1..n]  > 
premis_File --> premis_File :document [0..n]  \lfichier suivant dans l'ordre [0..1]  \lremplace [0..n]  > 
premis_File --> premis_Fixity :a fixity [1..1]  > 
premis_File --> premis_StorageLocation :stocké à [1..n]  > 



premis_Fixity : créateur de somme de contrôle : <i>xsd:string</i> [0..n]
premis_Fixity : vérification de la fixation : <i>xsd:string</i> [1..n]




haObj_LocalIdentifier --|> skos_Concept #blue;line.dotted;text:blue

haObj_LocalIdentifier : valeur : <i>xsd:string</i> [1..1]


premis_Object --|> prov_Entity #blue;line.dotted;text:blue

premis_Object --> premis_Object :a une relation [0..n]  > 

premis_Representation --|> premis_Object #blue;line.dotted;text:blue


haObj_DigitalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_DigitalRepresentation --> haObj_PhysicalRepresentation :a une source [0..n]  > 
haObj_DigitalRepresentation --> premis_File :est à la base de [0..n]  \linclut [1..n]  \lsource du fragment de média (MediaFragment) [0..n]  > 
haObj_DigitalRepresentation --> premis_IntellectualEntity :est copie d'accès de [0..1]  \lest format mezzanine de [0..1]  \lest la copie principale de [1..n]  \lreprésente [1..n]  > 

haObj_PhysicalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_PhysicalRepresentation --> premis_StorageMedium :a un support [0..n]  > 




hide circle
hide methods
hide empty members
@enduml


