@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>OpenCaptions</b> (ebucore:OpenCaptions)" as ebucore_OpenCaptions [[#ebucore%3AOpenCaptions]]
class "<b>Bobine audio</b> (haDes:AudioReel)" as haDes_AudioReel [[#haDes%3AAudioReel]]
class "<b>Bobine d'image</b> (haDes:ImageReel)" as haDes_ImageReel [[#haDes%3AImageReel]]
class "<b>Film</b> (haDes:Film)" as haDes_Film [[#haDes%3AFilm]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[../../terms/fr#skos%3AConcept]]
class "<b>représentation de porteur</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[../../dvd/fr#haObj%3ACarrierRepresentation]]
class "<b>représentation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]


ebucore_OpenCaptions : en langue : <i>xsd:string</i> [0..*]





haDes_ImageReel --> ebucore_OpenCaptions :a des sous-titres (intégrés) [0..*]  > 
haDes_ImageReel --> skos_Concept :type de coloration [0..1]  > 


haDes_Film --> haObj_CarrierRepresentation :est représenté par [1..*]  > 



haObj_CarrierRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_CarrierRepresentation : nombre de bobines : <i>xsd:decimal</i> [0..1]
haObj_CarrierRepresentation : nombre de bobines audio perdues : <i>xsd:decimal</i> [0..1]
haObj_CarrierRepresentation : nombre de bobines d'image perdues : <i>xsd:decimal</i> [0..1]
haObj_CarrierRepresentation --> haDes_AudioReel :stocké à [1..*]  > 
haObj_CarrierRepresentation --> haDes_ImageReel :stocké à [1..*]  > 



hide circle
hide methods
hide empty members
@enduml


