@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>NewspaperIssue</b> (haDes:NewspaperIssue)" as haDes_NewspaperIssue [[#haDes%3ANewspaperIssue]]
class "<b>NewspaperIssuePage</b> (haDes:NewspaperIssuePage)" as haDes_NewspaperIssuePage [[#haDes%3ANewspaperIssuePage]]
class "<b>Newspaper</b> (schema:Newspaper)" as schema_Newspaper [[#schema%3ANewspaper]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[../../terms/fr#skos%3AConcept]]


haDes_NewspaperIssue : nombre de pages : <i>xsd:decimal</i> [0..1]
haDes_NewspaperIssue : numéro de l'édition : <i>xsd:decimal</i> [0..1]
haDes_NewspaperIssue --> schema_Newspaper :fait partie de [0..1]  > 
haDes_NewspaperIssue --> skos_Concept :fréquence d'émission [0..1]  \ltype de publication [0..1]  > 



haDes_NewspaperIssuePage : numéro de page : <i>xsd:decimal</i> [0..1]
haDes_NewspaperIssuePage --> haDes_NewspaperIssue :fait partie de [1..1]  > 







hide circle
hide methods
hide empty members
@enduml


