@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 100
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left


class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Intellectual entity</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Physical representation</b> (haObj:PhysicalRepresentation)" as haObj_PhysicalRepresentation [[#haObj%3APhysicalRepresentation]]
class "<b>Representation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Digital representation</b> (haObj:DigitalRepresentation)" as haObj_DigitalRepresentation [[#haObj%3ADigitalRepresentation]]
class "<b>Representation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>File</b> (premis:File)" as premis_File [[#premis%3AFile]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Fixity</b> (premis:Fixity)" as premis_Fixity [[#premis%3AFixity]]
class "<b>Storage location</b> (premis:StorageLocation)" as premis_StorageLocation [[#premis%3AStorageLocation]]
class "<b>Local identifier</b> (haObj:LocalIdentifier)" as haObj_LocalIdentifier [[#haObj%3ALocalIdentifier]]
class "<b>File Format</b> (dct:FileFormat)" as dct_FileFormat [[#dct%3AFileFormat]]
class "<b>Storage medium</b> (premis:StorageMedium)" as premis_StorageMedium [[#premis%3AStorageMedium]]
class "<b>Representation</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]



premis_Object --> premis_Object : has relationship [0..n] >

premis_IntellectualEntity --|> premis_Object #blue;line.dotted;text:blue


premis_IntellectualEntity --> premis_IntellectualEntity : has Part [0..n] >

premis_IntellectualEntity --> haObj_DigitalRepresentation : has access copy [0..n] >

premis_IntellectualEntity --> haObj_DigitalRepresentation : has archiving master [0..1] >

premis_IntellectualEntity --> haObj_DigitalRepresentation : has mezzanine format [0..1] >

premis_IntellectualEntity --> premis_IntellectualEntity : is Part Of [0..n] >

premis_IntellectualEntity --> premis_Representation : is Represented by [0..n] >

premis_IntellectualEntity --> haObj_LocalIdentifier : local identifier [0..n] >

haObj_PhysicalRepresentation --|> premis_Representation #blue;line.dotted;text:blue


haObj_PhysicalRepresentation --> premis_StorageMedium : has medium [0..n] >

haObj_DigitalRepresentation --|> premis_Representation #blue;line.dotted;text:blue


haObj_DigitalRepresentation --> premis_File : Media fragment source [0..n] >

haObj_DigitalRepresentation --> premis_File : has Root [0..n] >

haObj_DigitalRepresentation --> haObj_PhysicalRepresentation : has Source [0..n] >

haObj_DigitalRepresentation --> premis_File : includes [1..n] >

haObj_DigitalRepresentation --> premis_IntellectualEntity : is access copy of [0..1] >

haObj_DigitalRepresentation --> premis_IntellectualEntity : is archiving master of [1..n] >

haObj_DigitalRepresentation --> premis_IntellectualEntity : is mezzanine format of [0..1] >

haObj_DigitalRepresentation --> premis_IntellectualEntity : represents [1..n] >

premis_File --|> premis_Object #blue;line.dotted;text:blue


premis_File --> dct_FileFormat : Format [1..1] >

premis_File --> premis_File : documents [0..n] >

premis_File --> premis_Fixity : has fixity [1..1] >

premis_File --> haObj_DigitalRepresentation : has media fragment [0..n] >

premis_File --> haObj_DigitalRepresentation : is Included in [1..n] >
premis_File : mime type : <i>xsd:string</i> [0..1]


premis_File --> premis_File : next file in sequence [0..1] >

premis_File --> premis_StorageLocation : stored at [1..n] >

premis_File --> premis_File : supersedes [0..n] >


premis_Fixity : checksum creator : <i>xsd:string</i> [0..n]

premis_Fixity : fixity checksum : <i>xsd:string</i> [1..n]



premis_StorageLocation : file path : <i>xsd:string</i> [1..n]


premis_StorageLocation --> premis_StorageMedium : milieu de stockage [0..n] >

premis_StorageLocation --> premis_StorageMedium : storage medium [0..n] >


haObj_LocalIdentifier : value : <i>xsd:string</i> [1..1]






premis_Representation --|> premis_Object #blue;line.dotted;text:blue



hide circle
hide methods
hide empty members
@enduml


