@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>Afbeelding</b> (haDes:Image)" as haDes_Image [[#haDes%3AImage]]
class "<b>Intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Audio</b> (haDes:Audio)" as haDes_Audio [[#haDes%3AAudio]]
class "<b>Intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Concept</b> (skos:Concept)" as skos_Concept [[../../terms/nl#skos%3AConcept]]
class "<b>Drager representatie</b> (haObj:CarrierRepresentation)" as haObj_CarrierRepresentation [[#haObj%3ACarrierRepresentation]]
class "<b>Representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>Dvd</b> (haDes:DVD)" as haDes_DVD [[#haDes%3ADVD]]
class "<b>Intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Dvd-hoofdstuk</b> (haDes:DVDChapter)" as haDes_DVDChapter [[#haDes%3ADVDChapter]]
class "<b>Intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Fysieke drager</b> (haObj:PhysicalCarrier)" as haObj_PhysicalCarrier [[#haObj%3APhysicalCarrier]]
class "<b>Opslagplaats</b> (premis:StorageLocation)" as premis_StorageLocation [[#premis%3AStorageLocation]]
class "<b>Video</b> (haDes:Video)" as haDes_Video [[#haDes%3AVideo]]
class "<b>Intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]

haDes_Image --|> premis_IntellectualEntity #blue;line.dotted;text:blue


haDes_Audio --|> premis_IntellectualEntity #blue;line.dotted;text:blue




haObj_CarrierRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_CarrierRepresentation : aantal audiokanalen : <i>xsd:nonNegativeInteger</i> [0..1]
haObj_CarrierRepresentation : aantal audiotracks : <i>xsd:nonNegativeInteger</i> [0..1]


haDes_DVD --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_DVD --> haDes_DVDChapter :heeft een onderdeel [0..*]  > 

haDes_DVDChapter --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haDes_DVDChapter : Dvd-hoofdstuknummer : <i>xsd:nonNegativeInteger</i> [1..1]
haDes_DVDChapter --> haDes_DVD :is onderdeel van [1..1]  > 


haObj_PhysicalCarrier --|> premis_StorageLocation #blue;line.dotted;text:blue

haObj_PhysicalCarrier : audio ruisonderdrukking : <i>xsd:string</i> [0..1]
haObj_PhysicalCarrier --> skos_Concept :audio-opnamesnelheid [0..1]  \liec-60094 type [0..1]  \liec-60094 type [0..1]  \liec-60094 type [0..1]  > 


haDes_Video --|> premis_IntellectualEntity #blue;line.dotted;text:blue



hide circle
hide methods
hide empty members
@enduml


