@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>Formele Organisatie</b> (org:FormalOrganization)" as org_FormalOrganization [[#org%3AFormalOrganization]]
class "<b>organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>aanspreek-/meldpunt</b> (schema:ContactPoint)" as schema_ContactPoint [[#schema%3AContactPoint]]
class "<b>activiteit</b> (prov:Activity)" as prov_Activity [[#prov%3AActivity]]
class "<b>aflevering</b> (schema:Episode)" as schema_Episode [[#schema%3AEpisode]]
class "<b>creatief werk</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>archiefcomponent</b> (schema:ArchiveComponent)" as schema_ArchiveComponent [[#schema%3AArchiveComponent]]
class "<b>creatief werk</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>bestand</b> (premis:File)" as premis_File [[#premis%3AFile]]
class "<b>object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>bestandsformaat</b> (dct:FileFormat)" as dct_FileFormat [[#dct%3AFileFormat]]
class "<b>collectie</b> (schema:Collection)" as schema_Collection [[#schema%3ACollection]]
class "<b>creatief werk</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>conceptenschema</b> (skos:ConceptScheme)" as skos_ConceptScheme [[#skos%3AConceptScheme]]
class "<b>contentpartner</b> (haOrg:ContentPartner)" as haOrg_ContentPartner [[#haOrg%3AContentPartner]]
class "<b>organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>dienstenafnemer</b> (haOrg:ServiceConsumer)" as haOrg_ServiceConsumer [[#haOrg%3AServiceConsumer]]
class "<b>organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>dienstenleverancier</b> (haOrg:ServiceProvider)" as haOrg_ServiceProvider [[#haOrg%3AServiceProvider]]
class "<b>organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>digitale representatie</b> (haObj:DigitalRepresentation)" as haObj_DigitalRepresentation [[#haObj%3ADigitalRepresentation]]
class "<b>representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>digitaliseringspartner</b> (haOrg:DigitizationPartner)" as haOrg_DigitizationPartner [[#haOrg%3ADigitizationPartner]]
class "<b>dienstenleverancier</b> (haOrg:ServiceProvider)" as haOrg_ServiceProvider [[#haOrg%3AServiceProvider]]
class "<b>educatieve partner</b> (haOrg:EducationalPartner)" as haOrg_EducationalPartner [[#haOrg%3AEducationalPartner]]
class "<b>organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>fixity</b> (premis:Fixity)" as premis_Fixity [[#premis%3AFixity]]
class "<b>fysieke representatie</b> (haObj:PhysicalRepresentation)" as haObj_PhysicalRepresentation [[#haObj%3APhysicalRepresentation]]
class "<b>representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>gebeurtenis</b> (premis:Event)" as premis_Event [[#premis%3AEvent]]
class "<b>activiteit</b> (prov:Activity)" as prov_Activity [[#prov%3AActivity]]
class "<b>geordende collectie</b> (skos:OrderedCollection)" as skos_OrderedCollection [[#skos%3AOrderedCollection]]
class "<b>verzameling</b> (skos:Collection)" as skos_Collection [[#skos%3ACollection]]
class "<b>hardware agent</b> (premis:HardwareAgent)" as premis_HardwareAgent [[#premis%3AHardwareAgent]]
class "<b>agent</b> (premis:Agent)" as premis_Agent [[#premis%3AAgent]]
class "<b>intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>kwantitatieve waarde</b> (schema:QuantitativeValue)" as schema_QuantitativeValue [[#schema%3AQuantitativeValue]]
class "<b>label</b> (skosxl:Label)" as skosxl_Label [[#skosxl%3ALabel]]
class "<b>land</b> (schema:Country)" as schema_Country [[#schema%3ACountry]]
class "<b>lijst</b> (rdf:List)" as rdf_List [[#rdf%3AList]]
class "<b>logo</b> (haOrg:Logo)" as haOrg_Logo [[#haOrg%3ALogo]]
class "<b>lokale identificatie</b> (haObj:LocalIdentifier)" as haObj_LocalIdentifier [[#haObj%3ALocalIdentifier]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>entiteit</b> (prov:Entity)" as prov_Entity [[#prov%3AEntity]]
class "<b>opslagmedium</b> (premis:StorageMedium)" as premis_StorageMedium [[#premis%3AStorageMedium]]
class "<b>opslagplaats</b> (premis:StorageLocation)" as premis_StorageLocation [[#premis%3AStorageLocation]]
class "<b>organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>organisatie-eenheid</b> (org:OrganizationalUnit)" as org_OrganizationalUnit [[#org%3AOrganizationalUnit]]
class "<b>organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>organisatietype</b> (haOrg:OrganizationType)" as haOrg_OrganizationType [[#haOrg%3AOrganizationType]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>persoon</b> (schema:Person)" as schema_Person [[#schema%3APerson]]
class "<b>plaats</b> (schema:Place)" as schema_Place [[#schema%3APlace]]
class "<b>positie</b> (org:Post)" as org_Post [[#org%3APost]]
class "<b>postadres</b> (schema:PostalAddress)" as schema_PostalAddress [[#schema%3APostalAddress]]
class "<b>aanspreek-/meldpunt</b> (schema:ContactPoint)" as schema_ContactPoint [[#schema%3AContactPoint]]
class "<b>projectpartner</b> (haOrg:ProjectPartner)" as haOrg_ProjectPartner [[#haOrg%3AProjectPartner]]
class "<b>organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>representatie</b> (premis:Representation)" as premis_Representation [[#premis%3ARepresentation]]
class "<b>object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>rol</b> (schema:Role)" as schema_Role [[#schema%3ARole]]
class "<b>rol</b> (org:Role)" as org_Role [[#org%3ARole]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>serie van het creatief werk</b> (schema:CreativeWorkSeries)" as schema_CreativeWorkSeries [[#schema%3ACreativeWorkSeries]]
class "<b>creatief werk</b> (schema:CreativeWork)" as schema_CreativeWork [[#schema%3ACreativeWork]]
class "<b>software agent</b> (premis:SoftwareAgent)" as premis_SoftwareAgent [[#premis%3ASoftwareAgent]]
class "<b>agent</b> (premis:Agent)" as premis_Agent [[#premis%3AAgent]]
class "<b>uitkomststatus</b> (premis:OutcomeStatus)" as premis_OutcomeStatus [[#premis%3AOutcomeStatus]]
class "<b>verzameling</b> (skos:Collection)" as skos_Collection [[#skos%3ACollection]]
class "<b>vestiging</b> (org:Site)" as org_Site [[#org%3ASite]]

org_FormalOrganization --|> org_Organization #blue;line.dotted;text:blue



schema_ContactPoint : contacttype : <i>xsd:string</i> [1..1]
schema_ContactPoint : e-mail : <i>xsd:string</i> [0..*]
schema_ContactPoint : telefoonnummer : <i>xsd:string</i> [0..*]



prov_Activity : heeft einddatum : <i>xsd:dateTime</i> [1..1]
prov_Activity : heeft gegenereerd : <i>IRI</i> [0..1]
prov_Activity : heeft startdatum : <i>xsd:dateTime</i> [1..1]

prov_Activity --> org_Organization :was toegekend aan [1..1]  > 
prov_Activity --> premis_HardwareAgent :was toegekend aan [1..1]  > 
prov_Activity --> premis_SoftwareAgent :was toegekend aan [1..1]  > 
prov_Activity --> schema_Person :was toegekend aan [1..1]  > 


schema_Episode --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_Episode : identifier : <i>xsd:string</i> [1..1]
schema_Episode : naam : <i>xsd:string</i> [1..1]
schema_Episode : omschrijving : <i>xsd:string</i> [1..1]


schema_ArchiveComponent --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_ArchiveComponent : naam : <i>xsd:string</i> [1..1]
schema_ArchiveComponent : omschrijving : <i>xsd:string</i> [1..1]


premis_File --|> premis_Object #blue;line.dotted;text:blue

premis_File : heeft (bestands)grootte : <i>xsd:nonNegativeInteger</i> [0..1]
premis_File : heeft originele naam : <i>xsd:string</i> [0..1]
premis_File : mime type : <i>xsd:string</i> [0..1]
premis_File --> dct_FileFormat :formaat [1..1]  > 
premis_File --> haObj_DigitalRepresentation :heeft media fragment [0..*]  \lis inbegrepen in [1..*]  > 
premis_File --> premis_File :documenteert [0..*]  \lvervangt [0..*]  \lvolgende bestand in volgorde [0..1]  > 
premis_File --> premis_Fixity :heeft fixity [1..1]  > 
premis_File --> premis_StorageLocation :opgeslagen te [1..*]  > 





schema_Collection --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_Collection : aantal items : <i>xsd:integer</i> [0..*]
schema_Collection : identifier : <i>xsd:string</i> [1..1]
schema_Collection : naam : <i>xsd:string</i> [1..1]
schema_Collection : omschrijving : <i>xsd:string</i> [1..1]
schema_Collection --> premis_IntellectualEntity :is deel van [0..*]  > 




skos_Concept : alternatief label : <i>rdf:langString</i> [0..*]
skos_Concept : definitie : <i>rdf:langString</i> [1..*]
skos_Concept : historische notitie : <i>rdf:langString</i> [0..*]
skos_Concept : notation : <i>xsd:string</i> [0..*]
skos_Concept : note : <i>rdf:langString</i> [0..*]
skos_Concept : redactionele notitie : <i>rdf:langString</i> [0..*]
skos_Concept : scope notitie : <i>rdf:langString</i> [0..*]
skos_Concept : verborgen label : <i>rdf:langString</i> [0..*]
skos_Concept : voorbeeld : <i>rdf:langString</i> [0..*]
skos_Concept : voorkeurslabel : <i>rdf:langString</i> [1..*]
skos_Concept : wijzigingsnotitie : <i>rdf:langString</i> [0..*]

skos_Concept --> skos_Concept :brede match [0..*]  \lbreder [0..*]  \lbreder transitief [0..*]  \lexacte overeenkomst [0..*]  \lgerelateerd [0..*]  \lgerelateerde match [0..*]  \lmapping relatie [0..*]  \lnabije match [0..*]  \lnauwe match [0..*]  \lnauwer [0..*]  \lnauwer transitief [0..*]  \lsemantische relatie [0..*]  > 
skos_Concept --> skos_ConceptScheme :in schema [1..*]  \ltop concept van [0..*]  > 
skos_Concept --> skosxl_Label :voorkeurslabel [0..1]  > 



skos_ConceptScheme : alternatief label : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : historische notitie : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : notation : <i>xsd:string</i> [0..*]
skos_ConceptScheme : note : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : redactionele notitie : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : scope notitie : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : verborgen label : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : voorbeeld : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : voorkeurslabel : <i>rdf:langString</i> [1..*]
skos_ConceptScheme : wijzigingsnotitie : <i>rdf:langString</i> [0..*]

skos_ConceptScheme --> skos_Concept :heeft top concept [0..*]  > 


haOrg_ContentPartner --|> org_Organization #blue;line.dotted;text:blue

haOrg_ContentPartner : heeft een identificator : <i>xsd:string</i> [1..1]
haOrg_ContentPartner : laat bezoekertool toe : <i>xsd:boolean</i> [1..1]
haOrg_ContentPartner : laat overlay toe : <i>xsd:boolean</i> [1..1]
haOrg_ContentPartner --> schema_Person :heeft account manager [1..1]  > 



haOrg_ServiceConsumer --|> org_Organization #blue;line.dotted;text:blue

haOrg_ServiceConsumer : heeft een identificator : <i>xsd:string</i> [1..1]


haOrg_ServiceProvider --|> org_Organization #blue;line.dotted;text:blue

haOrg_ServiceProvider : heeft een identificator : <i>xsd:string</i> [1..1]


haObj_DigitalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_DigitalRepresentation : aangemaakt op : <i>edtf:EDTF-level1</i> [1..1]
haObj_DigitalRepresentation : identifier : <i>xsd:string</i> [1..1]
haObj_DigitalRepresentation : naam : <i>xsd:string</i> [1..1]
haObj_DigitalRepresentation : omschrijving : <i>xsd:string</i> [1..1]
haObj_DigitalRepresentation : onderschrift : <i>xsd:string</i> [0..1]
haObj_DigitalRepresentation : transcriptie : <i>xsd:string</i> [0..1]

haObj_DigitalRepresentation --> haObj_PhysicalRepresentation :heeft een bron [0..*]  > 
haObj_DigitalRepresentation --> premis_File :bevat [1..*]  \lbron van het mediafragment (MediaFragment) [0..*]  \lligt aan de basis van [0..*]  > 
haObj_DigitalRepresentation --> premis_IntellectualEntity :is archiefmaster van [1..*]  \lis mezzanineformaat van [0..1]  \lis toegangskopie van [0..1]  \lrepresenteert [1..*]  > 
haObj_DigitalRepresentation --> schema_Role :auteur [0..*]  > 


haOrg_DigitizationPartner --|> haOrg_ServiceProvider #blue;line.dotted;text:blue

haOrg_DigitizationPartner : heeft een identificator : <i>xsd:string</i> [1..1]


haOrg_EducationalPartner --|> org_Organization #blue;line.dotted;text:blue

haOrg_EducationalPartner : heeft een identificator : <i>xsd:string</i> [1..1]
haOrg_EducationalPartner --> schema_Person :heeft account manager [1..1]  > 



premis_Fixity : checksum maker : <i>xsd:string</i> [0..*]
premis_Fixity : fixity checksum : <i>xsd:string</i> [1..*]


haObj_PhysicalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_PhysicalRepresentation : formaat : <i>xsd:string</i> [1..1]
haObj_PhysicalRepresentation : identifier : <i>xsd:string</i> [1..1]
haObj_PhysicalRepresentation : kunst medium : <i>xsd:string</i> [0..*]
haObj_PhysicalRepresentation : kunstvorm : <i>xsd:string</i> [0..*]
haObj_PhysicalRepresentation : medium : <i>xsd:string</i> [1..*]
haObj_PhysicalRepresentation : naam : <i>xsd:string</i> [1..1]
haObj_PhysicalRepresentation : omschrijving : <i>xsd:string</i> [1..1]
haObj_PhysicalRepresentation --> premis_StorageMedium :heeft als medium [0..*]  > 
haObj_PhysicalRepresentation --> schema_QuantitativeValue :breedte [0..*]  \ldiepte [0..*]  \lhoogte [0..*]  > 


premis_Event --|> prov_Activity #blue;line.dotted;text:blue

premis_Event : heeft opmerking : <i>xsd:string</i> [0..1]
premis_Event : heeft uitkomstopmerking : <i>xsd:string</i> [0..1]
premis_Event --> org_Organization :geimplementeerd door [1..1]  > 
premis_Event --> premis_HardwareAgent :uitgevoerd door [0..1]  > 
premis_Event --> premis_Object :heeft bron [0..1]  \lresultaat [0..1]  > 
premis_Event --> premis_OutcomeStatus :heeft uitkomst [0..1]  > 
premis_Event --> premis_SoftwareAgent :uitgevoerd door [0..1]  > 


skos_OrderedCollection --|> skos_Collection #blue;line.dotted;text:blue

skos_OrderedCollection : alternatief label : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : definitie : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : historische notitie : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : notation : <i>xsd:string</i> [0..*]
skos_OrderedCollection : note : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : redactionele notitie : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : scope notitie : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : verborgen label : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : voorbeeld : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : voorkeurslabel : <i>rdf:langString</i> [1..*]
skos_OrderedCollection : wijzigingsnotitie : <i>rdf:langString</i> [0..*]



premis_HardwareAgent --|> premis_Agent #blue;line.dotted;text:blue


premis_IntellectualEntity --|> premis_Object #blue;line.dotted;text:blue

premis_IntellectualEntity : aangemaakt op : <i>edtf:EDTF-level1</i> [0..1]
premis_IntellectualEntity : alternatieve naam : <i>xsd:string</i> [0..*]
premis_IntellectualEntity : auteursrechtenmelding : <i>xsd:string</i> [0..*]
premis_IntellectualEntity : beschikbaar op : <i>xsd:dateTime</i> [0..*]
premis_IntellectualEntity : copyright jaar : <i>xsd:integer</i> [0..*]
premis_IntellectualEntity : credittekst : <i>xsd:string</i> [0..*]
premis_IntellectualEntity : duur : <i>xsd:dateTime</i> [0..1]
premis_IntellectualEntity : genre : <i>xsd:string</i> [0..*]
premis_IntellectualEntity : gepubliceerd op : <i>edtf:EDTF-level1</i> [0..1]
premis_IntellectualEntity : identifier : <i>xsd:string</i> [1..1]
premis_IntellectualEntity : in taal : <i>xsd:string</i> [1..*]
premis_IntellectualEntity : naam : <i>xsd:string</i> [1..1]
premis_IntellectualEntity : omschrijving : <i>xsd:string</i> [1..1]
premis_IntellectualEntity : over : <i>IRI</i> [0..*]
premis_IntellectualEntity : samenvatting : <i>xsd:string</i> [0..1]
premis_IntellectualEntity : temporeel : <i>rdf:langString</i> [0..*]
premis_IntellectualEntity : trefwoorden : <i>xsd:string</i> [0..*]


premis_IntellectualEntity --> haObj_DigitalRepresentation :heeft archiefmaster [0..1]  \lheeft mezzanineformaat [0..1]  \lheeft toegangskopie [0..*]  > 
premis_IntellectualEntity --> haObj_LocalIdentifier :lokale identifier [0..*]  > 
premis_IntellectualEntity --> haOrg_ContentPartner :beheerder [1..1]  > 
premis_IntellectualEntity --> org_Organization :houder van auteursrecht [0..*]  > 
premis_IntellectualEntity --> premis_IntellectualEntity :heeft onderdeel [0..*]  \lmaakt onderdeel uit van [0..*]  > 
premis_IntellectualEntity --> premis_Representation :wordt gerepresenteerd door [0..*]  > 

premis_IntellectualEntity --> schema_ArchiveComponent :is een deel van [0..*]  > 
premis_IntellectualEntity --> schema_CreativeWorkSeries :is een deel van [0..*]  > 
premis_IntellectualEntity --> schema_Episode :is een deel van [0..*]  > 
premis_IntellectualEntity --> schema_Person :houder van auteursrecht [0..*]  > 
premis_IntellectualEntity --> schema_Place :spatiaal [0..*]  > 
premis_IntellectualEntity --> schema_Role :auteur [0..*]  \lbijdrager [0..*]  \luitgever [0..*]  > 
premis_IntellectualEntity --> skos_Concept :licentie [0..*]  > 





schema_QuantitativeValue : eenheidcode : <i>xsd:string</i> [0..*]
schema_QuantitativeValue : eenheidstekst : <i>xsd:string</i> [0..*]
schema_QuantitativeValue : waarde : <i>xsd:float</i> [0..*]




skosxl_Label : alternatief label : <i>rdf:langString</i> [0..*]
skosxl_Label : definitie : <i>rdf:langString</i> [1..*]
skosxl_Label : historische notitie : <i>rdf:langString</i> [0..*]
skosxl_Label : letterlijke vorm : <i>rdf:langString</i> [1..1]
skosxl_Label : notation : <i>xsd:string</i> [0..*]
skosxl_Label : note : <i>rdf:langString</i> [0..*]
skosxl_Label : redactionele notitie : <i>rdf:langString</i> [0..*]
skosxl_Label : scope notitie : <i>rdf:langString</i> [0..*]
skosxl_Label : verborgen label : <i>rdf:langString</i> [0..*]
skosxl_Label : voorbeeld : <i>rdf:langString</i> [0..*]
skosxl_Label : voorkeurslabel : <i>rdf:langString</i> [1..*]
skosxl_Label : wijzigingsnotitie : <i>rdf:langString</i> [0..*]






rdf_List --> skos_Collection :None [0..*]  > 
rdf_List --> skos_Concept :None [0..*]  > 



haObj_LocalIdentifier --|> skos_Concept #blue;line.dotted;text:blue

haObj_LocalIdentifier : waarde : <i>xsd:string</i> [1..1]


premis_Object --|> prov_Entity #blue;line.dotted;text:blue

premis_Object --> premis_Event :is gegenereerd door [0..1]  > 
premis_Object --> premis_Object :heeft een relatie [0..*]  > 




premis_StorageLocation : opslagpad : <i>xsd:string</i> [1..*]
premis_StorageLocation --> premis_StorageMedium :opslagmedium [0..*]  > 



org_Organization : alternatieve naam/label : <i>rdf:langString</i> [0..*]
org_Organization : beschrijving : <i>rdf:langString</i> [0..*]
org_Organization : heeft een identificator : <i>xsd:string</i> [0..1]
org_Organization : homepagina : <i>IRI</i> [0..1]
org_Organization : sector : <i>xsd:string</i> [0..1]
org_Organization : tenant naam : <i>xsd:string</i> [0..*]
org_Organization : voorkeursnaam/-label : <i>rdf:langString</i> [1..*]

org_Organization --> haOrg_Logo :logo [0..*]  > 
org_Organization --> haOrg_OrganizationType :classificatie [0..*]  > 
org_Organization --> org_OrganizationalUnit :heeft een eenheid [0..*]  > 
org_Organization --> org_Post :heeft positie [0..*]  > 
org_Organization --> org_Site :heeft primaire vestiging [0..1]  \lheeft vestiging [0..*]  > 

org_Organization --> schema_ContactPoint :aanspreekpunt [0..*]  > 
org_Organization --> schema_Person :heeft account manager [0..1]  > 


org_OrganizationalUnit --|> org_Organization #blue;line.dotted;text:blue

org_OrganizationalUnit --> org_Organization :organisatie-eenheid van [1..*]  > 

haOrg_OrganizationType --|> skos_Concept #blue;line.dotted;text:blue



schema_Person : email : <i>xsd:string</i> [0..*]
schema_Person : familienaam : <i>xsd:string</i> [1..1]
schema_Person : geboortedatum : <i>edtf:EDTF-level1</i> [0..1]
schema_Person : naam : <i>xsd:string</i> [0..1]
schema_Person : sterfdatum : <i>edtf:EDTF-level1</i> [0..1]
schema_Person : voornaam : <i>xsd:string</i> [1..1]

schema_Person --> org_Organization :is account manager van [0..*]  > 
schema_Person --> org_Post :heeft positie [0..*]  > 



schema_Place : naam : <i>xsd:string</i> [1..1]
schema_Place : omschrijving : <i>xsd:string</i> [1..1]



org_Post --> org_Organization :positie in [1..*]  > 
org_Post --> org_Role :rol [1..*]  > 

schema_PostalAddress --|> schema_ContactPoint #blue;line.dotted;text:blue

schema_PostalAddress : adres : <i>xsd:string</i> [0..1]
schema_PostalAddress : gemeente : <i>xsd:string</i> [0..1]
schema_PostalAddress : land : <i>xsd:string</i> [0..1]
schema_PostalAddress : postbusnummer : <i>xsd:string</i> [0..1]
schema_PostalAddress : postcode : <i>xsd:string</i> [0..1]
schema_PostalAddress : provincie : <i>xsd:string</i> [0..1]
schema_PostalAddress --> schema_Country :land [0..1]  > 


haOrg_ProjectPartner --|> org_Organization #blue;line.dotted;text:blue

haOrg_ProjectPartner : heeft een identificator : <i>xsd:string</i> [1..1]


premis_Representation --|> premis_Object #blue;line.dotted;text:blue



schema_Role : rolenaam : <i>xsd:string</i> [1..*]
schema_Role --> org_Organization :auteur [0..*]  \lbijdrager [0..*]  \luitgever [0..*]  > 
schema_Role --> schema_Person :acteur [0..*]  \lauteur [0..*]  \lbijdrager [0..*]  \luitgever [0..*]  > 
schema_Role --> skos_Concept :rolenaam [1..*]  > 


org_Role --|> skos_Concept #blue;line.dotted;text:blue

org_Role : voorkeursnaam/-label : <i>rdf:langString</i> [1..*]


schema_CreativeWorkSeries --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_CreativeWorkSeries : identifier : <i>xsd:string</i> [1..1]
schema_CreativeWorkSeries : naam : <i>xsd:string</i> [1..1]
schema_CreativeWorkSeries : omschrijving : <i>xsd:string</i> [1..1]
schema_CreativeWorkSeries : seizoensnummer : <i>xsd:integer</i> [0..*]



premis_SoftwareAgent --|> premis_Agent #blue;line.dotted;text:blue





skos_Collection : alternatief label : <i>rdf:langString</i> [0..*]
skos_Collection : definitie : <i>rdf:langString</i> [0..*]
skos_Collection : historische notitie : <i>rdf:langString</i> [0..*]
skos_Collection : notation : <i>xsd:string</i> [0..*]
skos_Collection : note : <i>rdf:langString</i> [0..*]
skos_Collection : redactionele notitie : <i>rdf:langString</i> [0..*]
skos_Collection : scope notitie : <i>rdf:langString</i> [0..*]
skos_Collection : verborgen label : <i>rdf:langString</i> [0..*]
skos_Collection : voorbeeld : <i>rdf:langString</i> [0..*]
skos_Collection : voorkeurslabel : <i>rdf:langString</i> [1..*]
skos_Collection : wijzigingsnotitie : <i>rdf:langString</i> [0..*]

skos_Collection --> skos_Collection :lid [0..*]  > 
skos_Collection --> skos_Concept :lid [0..*]  > 



org_Site --> org_Organization :vestiging van [1..1]  > 
org_Site --> schema_PostalAddress :adres van de vestiging [0..1]  > 


hide circle
hide methods
hide empty members
@enduml


