@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>Newspaper</b> (schema:Newspaper)" as schema_Newspaper [[#schema%3ANewspaper]]
class "<b>Kranteneditie</b> (haBib:NewspaperIssue)" as haBib_NewspaperIssue [[#haBib%3ANewspaperIssue]]
class "<b>intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Kranteneditiepagina</b> (haBib:NewspaperIssuePage)" as haBib_NewspaperIssuePage [[#haBib%3ANewspaperIssuePage]]
class "<b>intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[../../terms/nl#skos%3AConcept]]



haBib_NewspaperIssue --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haBib_NewspaperIssue : aantal pagina's : <i>xsd:decimal</i> [0..1]
haBib_NewspaperIssue : editienummer : <i>xsd:decimal</i> [0..1]
haBib_NewspaperIssue --> schema_Newspaper :maakt deel uit van [0..1]  > 
haBib_NewspaperIssue --> skos_Concept :uitgavefrequentie [0..1]  \luitgavetype [0..1]  > 


haBib_NewspaperIssuePage --|> premis_IntellectualEntity #blue;line.dotted;text:blue

haBib_NewspaperIssuePage : paginanummer : <i>xsd:decimal</i> [0..1]
haBib_NewspaperIssuePage --> haBib_NewspaperIssue :maakt deel uit van [1..1]  > 





hide circle
hide methods
hide empty members
@enduml


