@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 100
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left


class "<b>Intellectuele entiteit</b> (premis:IntellectualEntity)" as premis_IntellectualEntity [[#premis%3AIntellectualEntity]]
class "<b>Fysieke representatie</b> (haObj:PhysicalRepresentation)" as haObj_PhysicalRepresentation [[#haObj%3APhysicalRepresentation]]
class "<b>Digitale representatie</b> (haObj:DigitalRepresentation)" as haObj_DigitalRepresentation [[#haObj%3ADigitalRepresentation]]
class "<b>Serie van het creatief werk</b> (schema:CreativeWorkSeries)" as schema_CreativeWorkSeries [[#schema%3ACreativeWorkSeries]]
class "<b>Aflevering</b> (schema:Episode)" as schema_Episode [[#schema%3AEpisode]]
class "<b>Plaats</b> (schema:Place)" as schema_Place [[#schema%3APlace]]
class "<b>Archiefcomponent</b> (schema:ArchiveComponent)" as schema_ArchiveComponent [[#schema%3AArchiveComponent]]
class "<b>Rol</b> (schema:Role)" as schema_Role [[#schema%3ARole]]
class "<b>Persoon</b> (schema:Person)" as schema_Person [[#schema%3APerson]]
class "<b>Collectie</b> (schema:Collection)" as schema_Collection [[#schema%3ACollection]]
class "<b>Concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>Organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>Contentpartner</b> (haOrg:ContentPartner)" as haOrg_ContentPartner [[#haOrg%3AContentPartner]]

premis_IntellectualEntity --|> premis_Object #blue;line.dotted;text:blue

premis_IntellectualEntity : aangemaakt op : <i>edtf:EDTF-level1</i> [0..1]

premis_IntellectualEntity : alternatieve naam : <i>xsd:string</i> [0..n]


premis_IntellectualEntity --> "[0..n]" schema_Role : auteur >

premis_IntellectualEntity --> "[0..n]" schema_Person : auteur van de copyright >
premis_IntellectualEntity --> "[0..n]" org_Organization : auteur van de copyright >

premis_IntellectualEntity --> "[1..1]" haOrg_ContentPartner : beheerder >
premis_IntellectualEntity : beschikbaar op : <i>xsd:dateTime</i> [0..n]


premis_IntellectualEntity --> "[0..n]" schema_Role : bijdrager >
premis_IntellectualEntity : copyright jaar : <i>xsd:integer</i> [0..n]

premis_IntellectualEntity : copyright melding : <i>xsd:string</i> [0..n]

premis_IntellectualEntity : credit tekst : <i>xsd:string</i> [0..n]


premis_IntellectualEntity --> "[0..1]" schema_Episode : deel van aflevering >

premis_IntellectualEntity --> "[0..1]" schema_CreativeWorkSeries : deel van serie >
premis_IntellectualEntity : duur : <i>xsd:dateTime</i> [0..1]

premis_IntellectualEntity : genre : <i>xsd:string</i> [0..n]


premis_IntellectualEntity --> "[0..n]" schema_Place : geografische dekking >
premis_IntellectualEntity : gepubliceerd op : <i>edtf:EDTF-level1</i> [0..1]

premis_IntellectualEntity : identifier : <i>xsd:string</i> [1..1]

premis_IntellectualEntity : in taal : <i>xsd:string</i> [1..n]


premis_IntellectualEntity --> "[0..1]" schema_ArchiveComponent : is een deel van >

premis_IntellectualEntity --> "[0..n]" skos_Concept : licentie >
premis_IntellectualEntity : naam : <i>xsd:string</i> [1..1]

premis_IntellectualEntity : object type : <i>xsd:string</i> [0..1]

premis_IntellectualEntity : omschrijving : <i>xsd:string</i> [1..1]


premis_IntellectualEntity : samenvatting : <i>xsd:string</i> [0..1]

premis_IntellectualEntity : tijdsdekking : <i>xsd:string</i> [0..n]

premis_IntellectualEntity : trefwoorden : <i>xsd:string</i> [0..n]


premis_IntellectualEntity --> "[0..n]" schema_Role : uitgever >

haObj_PhysicalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_PhysicalRepresentation : formaat : <i>xsd:string</i> [1..1]

haObj_PhysicalRepresentation : formaat : <i>xsd:string</i> [1..1]

haObj_PhysicalRepresentation : identifier : <i>xsd:string</i> [1..1]

haObj_PhysicalRepresentation : medium : <i>xsd:string</i> [1..n]

haObj_PhysicalRepresentation : naam : <i>xsd:string</i> [1..1]

haObj_PhysicalRepresentation : omschrijving : <i>xsd:string</i> [1..1]


haObj_DigitalRepresentation --|> premis_Representation #blue;line.dotted;text:blue

haObj_DigitalRepresentation : aangemaakt op : <i>edtf:EDTF-level1</i> [1..1]


haObj_DigitalRepresentation --> "[0..n]" schema_Role : auteur >
haObj_DigitalRepresentation : identifier : <i>xsd:string</i> [1..1]

haObj_DigitalRepresentation : naam : <i>xsd:string</i> [1..1]

haObj_DigitalRepresentation : omschrijving : <i>xsd:string</i> [1..1]

haObj_DigitalRepresentation : onderschrift : <i>xsd:string</i> [0..1]

haObj_DigitalRepresentation : transcriptie : <i>xsd:string</i> [0..1]


schema_CreativeWorkSeries --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_CreativeWorkSeries : identifier : <i>xsd:string</i> [1..1]

schema_CreativeWorkSeries : naam : <i>xsd:string</i> [1..1]

schema_CreativeWorkSeries : omschrijving : <i>xsd:string</i> [1..1]

schema_CreativeWorkSeries : seizoensnummer : <i>xsd:integer</i> [0..n]


schema_Episode --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_Episode : identifier : <i>xsd:string</i> [1..1]

schema_Episode : naam : <i>xsd:string</i> [1..1]

schema_Episode : omschrijving : <i>xsd:string</i> [1..1]



schema_Place : naam : <i>xsd:string</i> [1..1]

schema_Place : omschrijving : <i>xsd:string</i> [1..1]


schema_ArchiveComponent --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_ArchiveComponent : naam : <i>xsd:string</i> [1..1]

schema_ArchiveComponent : omschrijving : <i>xsd:string</i> [1..1]




schema_Role --> "[0..n]" schema_Person : acteur >

schema_Role --> "[0..n]" schema_Person : auteur >
schema_Role --> "[0..n]" org_Organization : auteur >

schema_Role --> "[0..n]" schema_Person : bijdrager >
schema_Role --> "[0..n]" org_Organization : bijdrager >
schema_Role : rolenaam : <i>xsd:string</i> [1..n]

schema_Role --> "[1..n]" skos_Concept : rolenaam >

schema_Role --> "[0..n]" schema_Person : uitgever >
schema_Role --> "[0..n]" org_Organization : uitgever >


schema_Person : achternaam : <i>xsd:string</i> [0..n]

schema_Person : naam : <i>xsd:string</i> [1..1]

schema_Person : voornaam : <i>xsd:string</i> [0..n]


schema_Collection --|> schema_CreativeWork #blue;line.dotted;text:blue

schema_Collection : aantal items : <i>xsd:integer</i> [0..n]

schema_Collection : identifier : <i>xsd:string</i> [1..1]


schema_Collection --> "[0..n]" premis_IntellectualEntity : is deel van >
schema_Collection : naam : <i>xsd:string</i> [1..1]

schema_Collection : omschrijving : <i>xsd:string</i> [1..1]






haOrg_ContentPartner --|> org_Organization #blue;line.dotted;text:blue



hide circle
hide methods
hide empty members
@enduml


