@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 100
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left


class "<b>Activity</b> (prov:Activity)" as prov_Activity [[#prov%3AActivity]]
class "<b>Event</b> (premis:Event)" as premis_Event [[#premis%3AEvent]]
class "<b>Activity</b> (prov:Activity)" as prov_Activity [[#prov%3AActivity]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Entity</b> (prov:Entity)" as prov_Entity [[#prov%3AEntity]]
class "<b>Outcome status</b> (premis:OutcomeStatus)" as premis_OutcomeStatus [[#premis%3AOutcomeStatus]]
class "<b>Organization</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>Software agent</b> (premis:SoftwareAgent)" as premis_SoftwareAgent [[#premis%3ASoftwareAgent]]
class "<b>Agent</b> (premis:Agent)" as premis_Agent [[#premis%3AAgent]]
class "<b>Hardware agent</b> (premis:HardwareAgent)" as premis_HardwareAgent [[#premis%3AHardwareAgent]]
class "<b>Agent</b> (premis:Agent)" as premis_Agent [[#premis%3AAgent]]
class "<b>Person</b> (schema:Person)" as schema_Person [[#schema%3APerson]]


prov_Activity : has end date : <i>xsd:dateTime</i> [1..1]


prov_Activity : has start date : <i>xsd:dateTime</i> [1..1]


prov_Activity --> "[1..1]" premis_Object : was attributed to >
prov_Activity --> "[1..1]" schema_Person : was attributed to >
prov_Activity --> "[1..1]" org_Organization : was attributed to >
prov_Activity --> "[1..1]" premis_SoftwareAgent : was attributed to >
prov_Activity --> "[1..1]" premis_HardwareAgent : was attributed to >

premis_Event --|> prov_Activity #blue;line.dotted;text:blue


premis_Event --> "[0..1]" premis_SoftwareAgent : executed by >
premis_Event --> "[0..1]" premis_HardwareAgent : executed by >
premis_Event : has note : <i>xsd:string</i> [0..1]


premis_Event --> "[1..1]" premis_OutcomeStatus : has outcome >
premis_Event : has outcome note : <i>xsd:string</i> [0..1]


premis_Event --> "[0..1]" premis_Object : has source >

premis_Event --> "[1..1]" org_Organization : implemented by >

premis_Event --> "[0..1]" premis_Object : result >

premis_Object --|> prov_Entity #blue;line.dotted;text:blue


premis_Object --> "[0..1]" premis_Event : was generated by >





premis_SoftwareAgent --|> premis_Agent #blue;line.dotted;text:blue


premis_HardwareAgent --|> premis_Agent #blue;line.dotted;text:blue





hide circle
hide methods
hide empty members
@enduml


