@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 100
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left


class "<b>Organization</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>OrganizationalUnit</b> (org:OrganizationalUnit)" as org_OrganizationalUnit [[#org%3AOrganizationalUnit]]
class "<b>Organization</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>Content Partner</b> (haOrg:ContentPartner)" as haOrg_ContentPartner [[#haOrg%3AContentPartner]]
class "<b>Organization</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>Service Provider</b> (haOrg:ServiceProvider)" as haOrg_ServiceProvider [[#haOrg%3AServiceProvider]]
class "<b>Organization</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>Service Consumer</b> (haOrg:ServiceConsumer)" as haOrg_ServiceConsumer [[#haOrg%3AServiceConsumer]]
class "<b>Organization</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>Educational Organization</b> (haOrg:EducationalOrganization)" as haOrg_EducationalOrganization [[#haOrg%3AEducationalOrganization]]
class "<b>Organization</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>Educational Partner</b> (haOrg:EducationalPartner)" as haOrg_EducationalPartner [[#haOrg%3AEducationalPartner]]
class "<b>Educational Organization</b> (haOrg:EducationalOrganization)" as haOrg_EducationalOrganization [[#haOrg%3AEducationalOrganization]]
class "<b>Educational Publisher</b> (haOrg:EducationalPublisher)" as haOrg_EducationalPublisher [[#haOrg%3AEducationalPublisher]]
class "<b>Educational Organization</b> (haOrg:EducationalOrganization)" as haOrg_EducationalOrganization [[#haOrg%3AEducationalOrganization]]
class "<b>School</b> (haOrg:School)" as haOrg_School [[#haOrg%3ASchool]]
class "<b>Educational Organization</b> (haOrg:EducationalOrganization)" as haOrg_EducationalOrganization [[#haOrg%3AEducationalOrganization]]
class "<b>Site</b> (org:Site)" as org_Site [[#org%3ASite]]
class "<b>Post</b> (org:Post)" as org_Post [[#org%3APost]]
class "<b>Role</b> (org:Role)" as org_Role [[#org%3ARole]]
class "<b>Person</b> (schema:Person)" as schema_Person [[#schema%3APerson]]
class "<b>Postal address</b> (schema:PostalAddress)" as schema_PostalAddress [[#schema%3APostalAddress]]
class "<b>ContactPoint</b> (schema:ContactPoint)" as schema_ContactPoint [[#schema%3AContactPoint]]
class "<b>ContactPoint</b> (schema:ContactPoint)" as schema_ContactPoint [[#schema%3AContactPoint]]
class "<b>Logo</b> (haOrg:Logo)" as haOrg_Logo [[#haOrg%3ALogo]]
class "<b>Organization Type</b> (haOrg:OrganizationType)" as haOrg_OrganizationType [[#haOrg%3AOrganizationType]]


org_Organization : alternative label : <i>xsd:string</i> [0..n]


org_Organization --> "[0..n]" haOrg_OrganizationType : classification >

org_Organization --> "[0..n]" schema_ContactPoint : contact point >
org_Organization : description : <i>rdf:langString</i> [0..1]


org_Organization --> "[0..n]" org_OrganizationalUnit : has Unit >

org_Organization --> "[0..1]" schema_Person : has account manager >

org_Organization --> "[0..n]" org_Post : has post >

org_Organization --> "[0..1]" org_Site : has primary site >

org_Organization --> "[0..n]" org_Site : has site >


org_Organization --> "[0..n]" haOrg_Logo : logo >
org_Organization : preferred label : <i>xsd:string</i> [1..1]


org_OrganizationalUnit --|> org_Organization #blue;line.dotted;text:blue


org_OrganizationalUnit --> "[1..n]" org_Organization : unit of >

haOrg_ContentPartner --|> org_Organization #blue;line.dotted;text:blue


haOrg_ContentPartner --> "[1..1]" schema_Person : has account manager >

haOrg_ServiceProvider --|> org_Organization #blue;line.dotted;text:blue


haOrg_ServiceConsumer --|> org_Organization #blue;line.dotted;text:blue


haOrg_EducationalOrganization --|> org_Organization #blue;line.dotted;text:blue


haOrg_EducationalPartner --|> haOrg_EducationalOrganization #blue;line.dotted;text:blue


haOrg_EducationalPartner --> "[1..1]" schema_Person : has account manager >

haOrg_EducationalPublisher --|> haOrg_EducationalOrganization #blue;line.dotted;text:blue


haOrg_School --|> haOrg_EducationalOrganization #blue;line.dotted;text:blue




org_Site --> "[0..1]" schema_PostalAddress : site Address >



org_Post --> "[1..n]" org_Organization : post in >

org_Post --> "[1..n]" org_Role : role >


org_Role : preferred label : <i>xsd:string</i> [1..1]



schema_Person : email : <i>xsd:string</i> [0..n]

schema_Person : family name : <i>xsd:string</i> [1..n]

schema_Person : given name : <i>xsd:string</i> [1..n]


schema_Person --> "[0..n]" org_Post : holds >

schema_Person --> "[0..n]" org_Organization : is account manager of >

schema_PostalAddress --|> schema_ContactPoint #blue;line.dotted;text:blue

schema_PostalAddress : address : <i>xsd:string</i> [0..n]

schema_PostalAddress : country : <i>xsd:string</i> [0..n]

schema_PostalAddress : locality : <i>xsd:string</i> [0..n]

schema_PostalAddress : post office box number : <i>xsd:string</i> [0..n]

schema_PostalAddress : postal code : <i>xsd:string</i> [0..n]

schema_PostalAddress : region : <i>xsd:string</i> [0..n]



schema_ContactPoint : contact type : <i>xsd:string</i> [0..n]

schema_ContactPoint : email : <i>xsd:string</i> [0..n]

schema_ContactPoint : telephone : <i>xsd:string</i> [0..n]







hide circle
hide methods
hide empty members
@enduml


