@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 100
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left


class "<b>Organisatie</b> (org:Organization)" as org_Organization [[#org%3Aorganization]]
class "<b>Organisatie-eenheid</b> (org:OrganizationalUnit)" as org_OrganizationalUnit [[#org%3Aorganizationalunit]]
class "<b>Contentpartner</b> (haOrg:ContentPartner)" as haOrg_ContentPartner [[#haorg%3Acontentpartner]]
class "<b>Dienstenleverancier</b> (haOrg:ServiceProvider)" as haOrg_ServiceProvider [[#haorg%3Aserviceprovider]]
class "<b>Dienstenafnemer</b> (haOrg:ServiceConsumer)" as haOrg_ServiceConsumer [[#haorg%3Aserviceconsumer]]
class "<b>Educatieve organisatie</b> (haOrg:EducationalOrganization)" as haOrg_EducationalOrganization [[#haorg%3Aeducationalorganization]]
class "<b>Educatieve partner</b> (haOrg:EducationalPartner)" as haOrg_EducationalPartner [[#haorg%3Aeducationalpartner]]
class "<b>Educatieve uitgeverij</b> (haOrg:EducationalPublisher)" as haOrg_EducationalPublisher [[#haorg%3Aeducationalpublisher]]
class "<b>School</b> (haOrg:School)" as haOrg_School [[#haorg%3Aschool]]
class "<b>Vestiging</b> (org:Site)" as org_Site [[#org%3Asite]]
class "<b>Positie</b> (org:Post)" as org_Post [[#org%3Apost]]
class "<b>Rol</b> (org:Role)" as org_Role [[#org%3Arole]]
class "<b>Persoon</b> (schema:Person)" as schema_Person [[#schema%3Aperson]]
class "<b>Postadres</b> (schema:PostalAddress)" as schema_PostalAddress [[#schema%3Apostaladdress]]
class "<b>Aanspreek-/meldpunt</b> (schema:ContactPoint)" as schema_ContactPoint [[#schema%3Acontactpoint]]
class "<b>Logo</b> (haOrg:Logo)" as haOrg_Logo [[#haorg%3Alogo]]
class "<b>Organisatietype</b> (haOrg:OrganizationType)" as haOrg_OrganizationType [[#haorg%3Aorganizationtype]]



org_Organization --> "[0..n]" schema_ContactPoint : aanspreekpunt >
org_Organization : alternatieve naam/label : <i>xsd:string</i> [0..n]



org_Organization --> "[0..n]" haOrg_OrganizationType : classificatie >

org_Organization --> "[0..1]" schema_Person : heeft account manager >

org_Organization --> "[0..n]" org_OrganizationalUnit : heeft een eenheid >

org_Organization --> "[0..n]" org_Post : heeft positie >

org_Organization --> "[0..1]" org_Site : heeft primaire vestiging >

org_Organization --> "[0..n]" org_Site : heeft vestiging >


org_Organization --> "[1..n]" haOrg_Logo : logo >
org_Organization : voorkeursnaam/-label : <i>xsd:string</i> [1..1]


org_OrganizationalUnit --|> org_Organization #blue;line.dotted;text:blue


org_OrganizationalUnit --> "[1..n]" org_Organization : organisatie-eenheid van >

haOrg_ContentPartner --|> org_Organization #blue;line.dotted;text:blue


haOrg_ContentPartner --> "[1..1]" schema_Person : heeft account manager >

haOrg_ServiceProvider --|> org_Organization #blue;line.dotted;text:blue


haOrg_ServiceConsumer --|> org_Organization #blue;line.dotted;text:blue


haOrg_EducationalOrganization --|> org_Organization #blue;line.dotted;text:blue


haOrg_EducationalPartner --|> haOrg_EducationalOrganization #blue;line.dotted;text:blue


haOrg_EducationalPartner --> "[1..1]" schema_Person : heeft account manager >

haOrg_EducationalPublisher --|> haOrg_EducationalOrganization #blue;line.dotted;text:blue


haOrg_School --|> haOrg_EducationalOrganization #blue;line.dotted;text:blue




org_Site --> "[0..1]" schema_PostalAddress : adres van de vestiging >



org_Post --> "[1..n]" org_Organization : positie in >

org_Post --> "[1..n]" org_Role : rol >


org_Role : voorkeursnaam/-label : <i>xsd:string</i> [1..1]



schema_Person : email : <i>xsd:string</i> [0..n]

schema_Person : familienaam : <i>xsd:string</i> [1..n]


schema_Person --> "[0..n]" org_Post : heeft positie >

schema_Person --> "[0..n]" org_Organization : is account manager van >
schema_Person : voornaam : <i>xsd:string</i> [1..n]


schema_PostalAddress --|> schema_ContactPoint #blue;line.dotted;text:blue

schema_PostalAddress : adres : <i>xsd:string</i> [0..n]

schema_PostalAddress : gemeente : <i>xsd:string</i> [0..n]

schema_PostalAddress : land : <i>xsd:string</i> [0..n]

schema_PostalAddress : postbusnummer : <i>xsd:string</i> [0..n]

schema_PostalAddress : postcode : <i>xsd:string</i> [0..n]

schema_PostalAddress : provincie : <i>xsd:string</i> [0..n]



schema_ContactPoint : contacttype : <i>xsd:string</i> [0..n]

schema_ContactPoint : e-mail : <i>xsd:string</i> [0..n]

schema_ContactPoint : telefoonnummer : <i>xsd:string</i> [0..n]







hide circle
hide methods
hide empty members
@enduml


