@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>collection</b> (skos:Collection)" as skos_Collection [[#skos%3ACollection]]
class "<b>collection ordonnée</b> (skos:OrderedCollection)" as skos_OrderedCollection [[#skos%3AOrderedCollection]]
class "<b>collection</b> (skos:Collection)" as skos_Collection [[#skos%3ACollection]]
class "<b>concept</b> (skos:Concept)" as skos_Concept [[#skos%3AConcept]]
class "<b>liste</b> (rdf:List)" as rdf_List [[#rdf%3AList]]
class "<b>schéma de concepts</b> (skos:ConceptScheme)" as skos_ConceptScheme [[#skos%3AConceptScheme]]
class "<b>étiquette</b> (skosxl:Label)" as skosxl_Label [[#skosxl%3ALabel]]


skos_Collection : définition : <i>rdf:langString</i> [0..*]
skos_Collection : exemple : <i>rdf:langString</i> [0..*]
skos_Collection : notation : <i>xsd:string</i> [0..*]
skos_Collection : note : <i>rdf:langString</i> [0..*]
skos_Collection : note d'historique : <i>rdf:langString</i> [0..*]
skos_Collection : note de champ : <i>rdf:langString</i> [0..*]
skos_Collection : note de changement : <i>rdf:langString</i> [0..*]
skos_Collection : note éditoriale : <i>rdf:langString</i> [0..*]
skos_Collection : étiquette alternative : <i>rdf:langString</i> [0..*]
skos_Collection : étiquette cachée : <i>rdf:langString</i> [0..*]
skos_Collection : étiquette préférée : <i>rdf:langString</i> [1..*]

skos_Collection --> skos_Collection :membre [0..*]  > 
skos_Collection --> skos_Concept :membre [0..*]  > 


skos_OrderedCollection --|> skos_Collection #blue;line.dotted;text:blue

skos_OrderedCollection : définition : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : exemple : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : notation : <i>xsd:string</i> [0..*]
skos_OrderedCollection : note : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : note d'historique : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : note de champ : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : note de changement : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : note éditoriale : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : étiquette alternative : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : étiquette cachée : <i>rdf:langString</i> [0..*]
skos_OrderedCollection : étiquette préférée : <i>rdf:langString</i> [1..*]




skos_Concept : définition : <i>rdf:langString</i> [1..*]
skos_Concept : exemple : <i>rdf:langString</i> [0..*]
skos_Concept : notation : <i>xsd:string</i> [0..*]
skos_Concept : note : <i>rdf:langString</i> [0..*]
skos_Concept : note d'historique : <i>rdf:langString</i> [0..*]
skos_Concept : note de champ : <i>rdf:langString</i> [0..*]
skos_Concept : note de changement : <i>rdf:langString</i> [0..*]
skos_Concept : note éditoriale : <i>rdf:langString</i> [0..*]
skos_Concept : étiquette alternative : <i>rdf:langString</i> [0..*]
skos_Concept : étiquette cachée : <i>rdf:langString</i> [0..*]
skos_Concept : étiquette préférée : <i>rdf:langString</i> [1..*]

skos_Concept --> skos_Concept :a une priorité inférieure à [0..*]  \la une priorité plus grande que [0..*]  \lcorrespondance exacte [0..*]  \lcorrespondance large [0..*]  \lcorrespondance liée [0..*]  \lcorrespondance proche [0..*]  \lcorrespondance étroite [0..*]  \llié [0..*]  \lplus large [0..*]  \lplus large transitive [0..*]  \lplus étroit [0..*]  \lplus étroit transitive [0..*]  \lrelation de correspondance [0..*]  \lrelation sémantique [0..*]  > 
skos_Concept --> skos_ConceptScheme :concept supérieur de [0..*]  \ldans le schéma [1..*]  > 
skos_Concept --> skosxl_Label :label préféré [0..1]  > 



rdf_List --> skos_Collection :None [0..*]  > 
rdf_List --> skos_Concept :None [0..*]  > 


skos_ConceptScheme : exemple : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : notation : <i>xsd:string</i> [0..*]
skos_ConceptScheme : note : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : note d'historique : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : note de champ : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : note de changement : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : note éditoriale : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : étiquette alternative : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : étiquette cachée : <i>rdf:langString</i> [0..*]
skos_ConceptScheme : étiquette préférée : <i>rdf:langString</i> [1..*]

skos_ConceptScheme --> skos_Concept :a pour concept supérieur [0..*]  > 



skosxl_Label : forme littérale : <i>rdf:langString</i> [1..1]



hide circle
hide methods
hide empty members
@enduml


