@startuml
!theme vibrant
skinparam classFontSize 14
!define LIGHTORANGE
skinparam componentStyle uml2
skinparam wrapMessageWidth 1000
skinparam wrapWidth 1000
' skinparam ArrowColor #Maroon
' Remove shadows
skinparam shadowing false
'skinparam linetype polyline
skinparam ArrowMessageAlignment left
top to bottom direction


class "<b>Activiteit</b> (prov:Activity)" as prov_Activity [[#prov%3AActivity]]
class "<b>Gebeurtenis</b> (premis:Event)" as premis_Event [[#premis%3AEvent]]
class "<b>Activiteit</b> (prov:Activity)" as prov_Activity [[#prov%3AActivity]]
class "<b>Object</b> (premis:Object)" as premis_Object [[#premis%3AObject]]
class "<b>Entiteit</b> (prov:Entity)" as prov_Entity [[#prov%3AEntity]]
class "<b>Organisatie</b> (org:Organization)" as org_Organization [[#org%3AOrganization]]
class "<b>Persoon</b> (schema:Person)" as schema_Person [[#schema%3APerson]]
class "<b>Hardware agent</b> (premis:HardwareAgent)" as premis_HardwareAgent [[#premis%3AHardwareAgent]]
class "<b>Agent</b> (premis:Agent)" as premis_Agent [[#premis%3AAgent]]
class "<b>Uitkomststatus</b> (premis:OutcomeStatus)" as premis_OutcomeStatus [[#premis%3AOutcomeStatus]]
class "<b>Software agent</b> (premis:SoftwareAgent)" as premis_SoftwareAgent [[#premis%3ASoftwareAgent]]
class "<b>Agent</b> (premis:Agent)" as premis_Agent [[#premis%3AAgent]]


prov_Activity : heeft einddatum : <i>xsd:dateTime</i> [1..1]
prov_Activity : heeft startdatum : <i>xsd:dateTime</i> [1..1]

prov_Activity --> org_Organization :was toegekend aan [1..1]  > 
prov_Activity --> premis_HardwareAgent :was toegekend aan [1..1]  > 
prov_Activity --> premis_Object :was toegekend aan [1..1]  > 
prov_Activity --> premis_SoftwareAgent :was toegekend aan [1..1]  > 
prov_Activity --> schema_Person :was toegekend aan [1..1]  > 


premis_Event --|> prov_Activity #blue;line.dotted;text:blue

premis_Event : heeft opmerking : <i>xsd:string</i> [0..1]
premis_Event : heeft uitkomst opmerking : <i>xsd:string</i> [0..1]
premis_Event --> org_Organization :geimplementeerd door [1..1]  > 
premis_Event --> premis_HardwareAgent :uitgevoerd door [0..1]  > 
premis_Event --> premis_Object :heeft bron [0..1]  \lresultaat [0..1]  > 
premis_Event --> premis_OutcomeStatus :heeft uitkomst [1..1]  > 
premis_Event --> premis_SoftwareAgent :uitgevoerd door [0..1]  > 


premis_Object --|> prov_Entity #blue;line.dotted;text:blue

premis_Object --> premis_Event :is gegenereerd door [0..1]  > 





premis_HardwareAgent --|> premis_Agent #blue;line.dotted;text:blue




premis_SoftwareAgent --|> premis_Agent #blue;line.dotted;text:blue



hide circle
hide methods
hide empty members
@enduml


